### ISSUE TITLE
SUB or FUNCTION defined twice

### ISSUE THREAD

**Issue by mediamanire** [BrightcoveOS/Roku-Sample-App#1]
Hi everyone,
sorry but very much a newbie at the brightcove/roku development and I am trying to understand an error I get. 

Can someone please help. I have downloaded and attempted to install the latest roku-sample-app but keep getting the following error.

ERROR compiling /pkg:/source/appHomeScreen.brs:
SUB or FUNCTION defined twice. (compile error &had) in ...pkg:source/appHomeScreen.brs (35)

Line 35 in the appHomeScreen.brs file reads as:

Function showHomeScreen(screen) As Integer

How do I resolve this problem? I am sure there is a 'common sense' answer but thats the problem (common sense!!). I presume that I would have to load all of the files in your zip to the roku after adding my brightcove token and unique player ID data or is there some 'files' that I should not be uploading. sorry if this does not make sense but I am quite literally a newbite. 
Please advise/help. Thanks for reading this.
Regards
Mediaman

**Comment by bdeitte** [comment]
A very late reply here, but glad to hear this was figured out.  I'm spending a bit of time trying to update this app this week, and I have a version that works with @jeffehobbs changes and a few of my own at https://github.com/bdeitte/Roku-Sample-App.  It will have a more permanent home later in the week.

**Comment by bdeitte** [comment]
This should be fixed with https://github.com/BrightcoveOS/Roku-Sample-App/pull/8
