### ISSUE TITLE
Unable to side-load / install to Roku

### ISSUE THREAD

**Issue by aaroncolon** [BrightcoveOS/Roku-Sample-App#3]
Hello,

I'm having some trouble side-loading this application to my Roku XD:

1. I've only modified the Config.brs with my Brightcove credentials per the readme and left everything else untouched
2. I've created the brightcoveplayer.zip using "make" (I'm on OS X)
3. Upon attempting to side-load to my Roku via my browser I receive this message: "Application Received: 238558 bytes stored. Install Failure: Compilation Failed."
4. Additionally, after setting my ROKU_DEV_TARGET variable, I've also tried using the "make install" command but receive a similar message: "Install Failure: Compilation Failed. < / font >" (yes, the < / font > tag is included in the failure message).

What am I missing?

Thanks,
Aaron

**Comment by bdeitte** [comment]
Hi @aaroncolon sorry for an insanely late reply.  As you may have noticed this app didn't really have an owner.  I'm trying to make some fixes up this week, and you may be happy to know that things are now working here in https://github.com/bdeitte/Roku-Sample-App (two years later, again apologies!)

**Comment by bdeitte** [comment]
This should be fixed with https://github.com/BrightcoveOS/Roku-Sample-App/pull/8
